name: Deploy Terraform

on:
  push:
    branches:
      - main
      - development

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file=${{ github.ref == 'refs/heads/main' && 'prod.tfvars' || 'dev.tfvars' }}

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file=${{ github.ref == 'refs/heads/main' && 'prod.tfvars' || 'dev.tfvars' }}
